name: Black Code Style Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  check-black:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install Black 24.10.0 - check setup.py if version matches
      run: |
        python -m pip install --upgrade pip
        pip install black==24.10.0
    - name: Run Black
      run: |
        black --check . --line-length 120
